///////////////////////////////////////////////
//IMOENS ERWEITERTER AUFTRITT IN KERZENBURG
///////////////////////////////////////////////

COMPILE EVALUATE_BUFFER ~%MOD_FOLDER%/Imoen_candlekeep/JA#IMOEN1.D~
EXTEND_TOP ~BGIMOEN.BCS~ ~%MOD_FOLDER%/Imoen_candlekeep/JA#IMOEN1.BAF~ EVALUATE_BUFFER
EXTEND_TOP ~%Candlekeep_Inn_L1%.BCS~ ~%MOD_FOLDER%/Imoen_candlekeep/AR6516.BAF~ EVALUATE_BUFFER
EXTEND_TOP ~%Candlekeep_Inn_L2%.BCS~ ~%MOD_FOLDER%/Imoen_candlekeep/AR6517.BAF~ EVALUATE_BUFFER