IF
	OR(2)
		Global("JA#RamazithDeal","GLOBAL",0)
		Global("JA#RamazithDeal","GLOBAL",10)
	Global("RamazithMove","GLOBAL",2)
	Global("JA#RAMAZITH_AR7241","%NBaldursGate_RamazithsTower_L4%",0)
	!Dead("Ramazith")
THEN
	RESPONSE #100
		SetGlobal("JA#RAMAZITH_AR7241","%NBaldursGate_RamazithsTower_L4%",1)
		CreateCreature("ELEMEP08",[78.235],15)
		CreateCreature("MEPICE01",[172.140],6)
		CreateCreature("MEPSAL01",[424.286],1)
END